#!/bin/bash

set -u
set -e
set -x
# shopt -s dotglob

options="--archive --protect-args --force-change --acls --xattrs --one-file-system --itemize-changes --crtimes --hard-links --omit-dir-times --delete --delete-excluded --safe-links"
# other options: --dry-run

exclude="--exclude-from=exclusions/to-TimeCop"

rsync $options $exclude $HOME/ /Volumes/TimeCop/CMM\ MBP
